; LC-3 third edition: TRAP pushes PC/PSR. Services return with RTI.
; Each unused trap/interrupt vector enters the fault handler.
.ORIG x0000
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_GETC
.FILL OS_OUT
.FILL OS_PUTS
.FILL OS_IN
.FILL OS_PUTSP
.FILL OS_HALT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_KEYBOARD
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
.FILL OS_FAULT
OS_GETC ADD R6, R6, #-1
STR R1, R6, #0
OS_GETC_WAIT LDI R1, OS_KBSR
BRzp OS_GETC_WAIT
LDI R0, OS_KBDR
LDR R1, R6, #0
ADD R6, R6, #1
RTI

OS_OUT ADD R6, R6, #-1
STR R1, R6, #0
OS_OUT_WAIT LDI R1, OS_DSR
BRzp OS_OUT_WAIT
STI R0, OS_DDR
LDR R1, R6, #0
ADD R6, R6, #1
RTI

OS_PUTS ADD R6, R6, #-2
STR R0, R6, #0
STR R1, R6, #1
ADD R1, R0, #0
OS_PUTS_LOOP LDR R0, R1, #0
BRz OS_PUTS_DONE
OUT
ADD R1, R1, #1
BR OS_PUTS_LOOP
OS_PUTS_DONE LDR R0, R6, #0
LDR R1, R6, #1
ADD R6, R6, #2
RTI

OS_IN LEA R0, OS_PROMPT
PUTS
GETC
OUT
RTI

; PUTSP extracts the high byte with a 16-bit doubling loop.
OS_PUTSP ADD R6, R6, #-5
STR R0, R6, #0
STR R1, R6, #1
STR R2, R6, #2
STR R3, R6, #3
STR R4, R6, #4
ADD R1, R0, #0
OS_PACK_LOOP LDR R2, R1, #0
BRz OS_PACK_DONE
LD R3, OS_BYTE_MASK
AND R0, R2, R3
OUT
AND R3, R3, #0
AND R4, R4, #0
ADD R4, R4, #8
OS_HIGH_LOOP ADD R3, R3, R3
ADD R2, R2, #0
BRzp OS_HIGH_ZERO
ADD R3, R3, #1
OS_HIGH_ZERO ADD R2, R2, R2
ADD R4, R4, #-1
BRp OS_HIGH_LOOP
ADD R0, R3, #0
BRz OS_PACK_NEXT
OUT
OS_PACK_NEXT ADD R1, R1, #1
BR OS_PACK_LOOP
OS_PACK_DONE LDR R0, R6, #0
LDR R1, R6, #1
LDR R2, R6, #2
LDR R3, R6, #3
LDR R4, R6, #4
ADD R6, R6, #5
RTI

; The default keyboard ISR echoes and consumes the pending byte.
OS_KEYBOARD ADD R6, R6, #-1
STR R0, R6, #0
LDI R0, OS_KBDR
OUT
LDR R0, R6, #0
ADD R6, R6, #1
RTI

; The fault handler keeps R0 for HALT, which preserves the remaining registers.
; If the clock is re-enabled, RTI re-executes the faulting instruction.
OS_FAULT ADD R6, R6, #-1
STR R0, R6, #0
LEA R0, OS_FAULT_TEXT
PUTS
LDR R0, R6, #0
ADD R6, R6, #1
HALT
RTI

; HALT restores R0-R5 and R7 before it stops the clock. The final MCR write
; needs a source register, so it uses the supervisor R6; the program's stack
; pointer stays in the saved USP. Re-enabling the clock returns after HALT.
OS_HALT ADD R6, R6, #-2
STR R0, R6, #0
STR R1, R6, #1
LEA R0, OS_HALT_TEXT
PUTS
LDI R0, OS_MCR
LD R1, OS_CLOCK_MASK
AND R0, R0, R1
ST R0, OS_MCR_STOP
LDR R0, R6, #0
LDR R1, R6, #1
ADD R6, R6, #2
ST R6, OS_HALT_SSP
LD R6, OS_MCR_STOP
STI R6, OS_MCR
LD R6, OS_HALT_SSP
RTI

OS_KBSR .FILL xFE00
OS_KBDR .FILL xFE02
OS_DSR .FILL xFE04
OS_DDR .FILL xFE06
OS_MCR .FILL xFFFE
OS_BYTE_MASK .FILL x00FF
OS_CLOCK_MASK .FILL x7FFF
OS_MCR_STOP .BLKW #1
OS_HALT_SSP .BLKW #1
OS_PROMPT .STRINGZ "Enter a character: "
OS_FAULT_TEXT .STRINGZ "LC-3 exception"
OS_HALT_TEXT .FILL x000A
.FILL x0048
.FILL x0041
.FILL x004C
.FILL x0054
.FILL x000A
.FILL x0000
.END
