export const sourceLines = [
  ".ORIG x3000",
  "",
  "; Read characters until Enter,",
  "; then print the buffered line.",
  "LEA   R1, BUFFER",
  "AND   R2, R2, #0",
  "",
  "READ  GETC",
  "OUT",
  "ADD   R3, R0, #-10",
  "BRz   PRINT",
  "STR   R0, R1, #0",
  "ADD   R1, R1, #1",
  "ADD   R2, R2, #1",
  "BRnzp READ",
  "",
  "PRINT LEA   R0, NEWLINE",
  "PUTS",
  "LEA   R0, BUFFER",
  "PUTS",
  "HALT",
  "",
  'NEWLINE .STRINGZ "\\n"',
  "BUFFER  .BLKW #32",
  ".END",
];

export const instructions = [
  {
    address: "x3000",
    label: "",
    opcode: "LEA",
    operands: "R1, x3017",
    hex: "E216",
    source: 5,
  },
  {
    address: "x3001",
    label: "",
    opcode: "AND",
    operands: "R2, R2, #0",
    hex: "54A0",
    source: 6,
  },
  {
    address: "x3002",
    label: "READ",
    opcode: "GETC",
    operands: "",
    hex: "F020",
    source: 8,
  },
  {
    address: "x3003",
    label: "",
    opcode: "OUT",
    operands: "",
    hex: "F021",
    source: 9,
  },
  {
    address: "x3004",
    label: "",
    opcode: "ADD",
    operands: "R3, R0, #-10",
    hex: "1636",
    source: 10,
  },
  {
    address: "x3005",
    label: "",
    opcode: "BRz",
    operands: "x300B",
    hex: "0405",
    source: 11,
  },
  {
    address: "x3006",
    label: "",
    opcode: "STR",
    operands: "R0, R1, #0",
    hex: "7040",
    source: 12,
  },
  {
    address: "x3007",
    label: "",
    opcode: "ADD",
    operands: "R1, R1, #1",
    hex: "1261",
    source: 13,
  },
  {
    address: "x3008",
    label: "",
    opcode: "ADD",
    operands: "R2, R2, #1",
    hex: "14A1",
    source: 14,
  },
  {
    address: "x3009",
    label: "",
    opcode: "BRnzp",
    operands: "x3002",
    hex: "0FF8",
    source: 15,
  },
  {
    address: "x300A",
    label: "",
    opcode: "NOP",
    operands: "",
    hex: "0000",
    source: 16,
  },
  {
    address: "x300B",
    label: "PRINT",
    opcode: "LEA",
    operands: "R0, x3016",
    hex: "E00A",
    source: 17,
  },
  {
    address: "x300C",
    label: "",
    opcode: "PUTS",
    operands: "",
    hex: "F022",
    source: 18,
  },
  {
    address: "x300D",
    label: "",
    opcode: "LEA",
    operands: "R0, x3017",
    hex: "E009",
    source: 19,
  },
  {
    address: "x300E",
    label: "",
    opcode: "PUTS",
    operands: "",
    hex: "F022",
    source: 20,
  },
  {
    address: "x300F",
    label: "",
    opcode: "HALT",
    operands: "",
    hex: "F025",
    source: 21,
  },
];

export const registers = [
  { name: "R0", hex: "x0068", signed: "104", changed: true },
  { name: "R1", hex: "x3019", signed: "12313", changed: true },
  { name: "R2", hex: "x0002", signed: "2", changed: true },
  { name: "R3", hex: "x005E", signed: "94", changed: false },
  { name: "R4", hex: "x0000", signed: "0", changed: false },
  { name: "R5", hex: "x0000", signed: "0", changed: false },
  { name: "R6", hex: "xFDFC", signed: "-516", changed: false },
  { name: "R7", hex: "x02F5", signed: "757", changed: false },
];

export const files = [
  { name: "echo.asm", active: true, dirty: true },
  { name: "stack.asm", active: false, dirty: false },
  { name: "strings.asm", active: false, dirty: false },
];
